services:
  - type: web
    name: FoodFinderBD
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y gdal-bin libgdal-dev
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn FoodFinder.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.cykmpvveglgbhtaazave:Zbn.V!#F9eKHHGB@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
