# Generated by Django 5.1.2 on 2024-10-18 16:25

import django.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=django.db.models.fields.CharField(blank=True, null=True, max_length=255),
        ),
    ]
